import {item} from "../models/item"

export const items:item[]=[

        
        new item("Moto Z1",11990,"Mobile",1,"moto","assets/img/mobile/img1.jpg"),
       
        new item("Honor",9990,"Mobile",2,"honor","assets/img/mobile/img2.jpg"),
        new item("Oppo",7990,"Mobile",3,"oppo","assets/img/mobile/img3.jpg"),
        new item("Mi note 4",11990,"Mobile",4,"xiaomi","assets/img/mobile/img4.jpg"),
        new item("Vivo",12990,"Mobile",5,"vivo","assets/img/mobile/img5.jpg"),

        new item("Moto g3s",13990,"Mobile",6,"moto","assets/img/mobile/img6.jpg"),
        new item("Moto g2s",11990,"Mobile",7,"moto","assets/img/mobile/img7.jpg"),
        new item("Micromax q2",6990,"Mobile",8,"micromax","assets/img/mobile/img8.jpg"),
        new item("Asus z1",8990,"Mobile",9,"asus","assets/img/mobile/img9.jpg"),

        new item("Moto G5",13990,"Mobile",10,"moto","assets/img/mobile/img10.jpg"),
        new item("Nokia",15990,"Mobile",11,"nokia","assets/img/mobile/img11.jpg"),
        new item("unite2",5990,"Mobile",12,"micromax","assets/img/mobile/img12.jpg"),
        new item("J7 pro",18990,"Mobile",13,"samsung","assets/img/mobile/img19.jpg"),

        new item("J5",15990,"Mobile",14,"samsung","assets/img/mobile/img20.jpg"),
        new item("z1",8690,"Mobile",15,"zenfone","assets/img/mobile/img21.jpg"),
        new item("J1",16999,"Mobile",16,"samsung","assets/img/mobile/img5.jpg"),
        new item("Moto g1",15900,"Mobile",17,"lenevo","assets/img/mobile/img6.jpg"),
        new item("Lenevo",13350,"Mobile",18,"lenevo","assets/img/mobile/img12.jpg"),
        // new item("Sony Xperia",19999,"Mobile",3,"Sony","assets/img/mobile/img9.jpg"),
        
        new item("Jeans",550,"Men",19,"cloth","assets/img/men/img8.jpg"),
        new item("Jeans",690,"Men",20,"cloth","assets/img/men/img9.jpg"),
        new item("Jeans",550,"Men",21,"cloth","assets/img/men/img10.jpg"),
        new item("Jeans",850,"Men",22,"cloth","assets/img/men/img11.jpg"),
        new item("shirt",550,"Men",23,"cloth","assets/img/men/img12.jpg"),
        new item("shirt",1550,"Men",24,"cloth","assets/img/men/img13.jpg"),
        new item("shirt",450,"Men",25,"cloth","assets/img/men/img14.jpg"),
        new item("shirt",600,"Men",26,"cloth","assets/img/men/img15.jpg"),
        new item("shirt",990,"Men",27,"cloth","assets/img/men/img16.jpg"),
        new item("shirt",760,"Men",28,"cloth","assets/img/men/img17.jpg"),
        new item("shirt",460,"Men",29,"cloth","assets/img/men/img18.jpg"),
        new item("shirt",1760,"Men",30,"cloth","assets/img/men/img19.jpg"),
        new item("shirt",860,"Men",31,"cloth","assets/img/men/img20.jpg"),
        new item("shirt",1760,"Men",32,"cloth","assets/img/men/img19.jpg"),                                                                                                                                                                                                                                                                                                    
        new item("top",1750,"Women",33,"cloth","assets/img/women/img1.jpg"),  
        new item("plazo",750,"Women",34,"cloth","assets/img/women/img2.jpg"),  
        new item("plazo",1750,"Women",35,"cloth","assets/img/women/img3.jpg"),  
        new item("top",590,"Women",36,"cloth","assets/img/women/img4.jpg"),  
        new item("western dress",1750,"Women",37,"cloth","assets/img/women/img5.jpg"),  
        new item("shrug",850,"Women",38,"cloth","assets/img/women/img6.jpg"),  
        new item("dress",2750,"Women",39,"cloth","assets/img/women/img7.jpg"),  
        new item("2 tops",1550,"Women",40,"cloth","assets/img/women/img8.jpg"),  
        new item("lehnga",950,"Women",41,"cloth","assets/img/women/img9.jpg"),  
        new item("jeans",670,"Women",42,"cloth","assets/img/women/img10.jpg"),  
        new item("legging",790,"Women",43,"cloth","assets/img/women/img11.jpg"),  
        new item("top",750,"Women",44,"cloth","assets/img/women/img12.jpg"),  
        new item("top",780,"Women",45,"cloth","assets/img/women/img13.jpg"),  
        new item("Pink dress",2750,"Women",46,"cloth","assets/img/women/img14.jpg"),  
        new item("top",950,"Women",47,"cloth","assets/img/women/img15.jpg"),  
        new item("peach dress",1050,"Women",48,"cloth","assets/img/women/img16.jpg"),  
        new item("top+jeans",3750,"Women",49,"cloth","assets/img/women/img17.jpg"),  
        new item("Blue dress",4750,"Women",50,"cloth","assets/img/women/img18.jpg"),  
        new item("jeans",750,"Women",51,"cloth","assets/img/women/img19.jpg"),  
        new item("shirt",450,"Women",52,"cloth","assets/img/women/img20.jpg"),  
        new item("shirt",750,"Women",53,"cloth","assets/img/women/img21.jpg"),  
        new item("t-shirt",795,"Women",54,"cloth","assets/img/women/img22.jpg"), 
        new item("t-shirt",590,"Women",55,"cloth","assets/img/women/img22.jpg"),  
        new item("gym",1750,"Sports",56,"sports","assets/img/sports/img1.jpg"), 
        new item("gym",1750,"Sports",57,"sports","assets/img/sports/img2.jpg"), 
        new item("gym",1750,"Sports",58,"sports","assets/img/sports/img3.jpg"), 
        new item("gym",1750,"Sports",59,"sports","assets/img/sports/img4.jpg"), 
        new item("gym",1750,"Sports",60,"sports","assets/img/sports/img5.jpg"), 
        new item("gym",1750,"Sports",61,"sports","assets/img/sports/img6.jpg"), 
        new item("gym",2750,"Sports",62,"sports","assets/img/sports/img7.jpg"), 
        new item("gym",1750,"Sports",63,"sports","assets/img/sports/img8.jpg"), 
        new item("ball",490,"Sports",64,"ball","assets/img/sports/img9.jpg"),         
        new item("pad",650,"Sports",65,"sports","assets/img/sports/img10.jpg"), 
        new item("gloves",750,"Sports",66,"sports","assets/img/sports/img11.jpg"), 
        new item("bat",1750,"Sports",67,"sports","assets/img/sports/img12.jpg"), 
        new item("ball",650,"Sports",68,"sports","assets/img/sports/img13.jpg"), 
        new item("ball",350,"Sports",69,"sports","assets/img/sports/img14.jpg"), 
        new item("combo(bat +gloves+ 2 tennis ball + 3 body pad+ 2 grip",2750,"Sports",70,"sports","assets/img/sports/img15.jpg"), 
        new item("bat",1550,"Sports",71,"sports","assets/img/sports/img16.jpg"), 
        new item("hometheater",5550,"Electronics",72,"electronics","assets/img/electronics/img1.jpg"), 
        new item("hometheater",5550,"Electronics",73,"electronics","assets/img/electronics/img2.jpg"), 
        new item("hometheater",5550,"Electronics",74,"electronics","assets/img/electronics/img3.jpg"), 
        new item("hometheater",5550,"Electronics",75,"electronics","assets/img/electronics/img4.jpg"), 
        new item("hometheater",5550,"Electronics",76,"electronics","assets/img/electronics/img5.jpg"), 
        new item("hometheater",5550,"Electronics",77,"electronics","assets/img/electronics/img6.jpg"), 
        new item("hometheater",5550,"Electronics",78,"electronics","assets/img/electronics/img7.jpg"), 
        new item("hometheater",5550,"Electronics",79,"electronics","assets/img/electronics/img8.jpg"), 
        new item("Split- Ac",5550,"Electronics",80,"electronics","assets/img/electronics/img9.jpg"), 
        new item("Split-Ac",5550,"Electronics",81,"electronics","assets/img/electronics/img10.jpg"), 
        new item("window-ac",5550,"Electronics",82,"electronics","assets/img/electronics/img11.jpg"), 
        new item("window-ac",5550,"Electronics",83,"electronics","assets/img/electronics/img12.jpg"), 
        new item("split-ac",5550,"Electronics",84,"electronics","assets/img/electronics/img13.jpg"), 
        new item("split-ac",5550,"Electronics",85,"electronics","assets/img/electronics/img14.jpg"), 
        new item("split-ac",5550,"Electronics",86,"electronics","assets/img/electronics/img15.jpg"), 
        new item("split-ac",5550,"Electronics",87,"electronics","assets/img/electronics/img16.jpg"), 
        new item("Refrigerator",5550,"Electronics",88,"electronics","assets/img/electronics/img17.jpg"), 
        new item("Refrigerator",5550,"Electronics",89,"electronics","assets/img/electronics/img18.jpg"), 
        new item("Refrigerator",5550,"Electronics",90,"electronics","assets/img/electronics/img19.jpg"), 
        new item("Refrigerator",5550,"Electronics",91,"electronics","assets/img/electronics/img20.jpg"), 
        new item("Refrigerator",5550,"Electronics",92,"electronics","assets/img/electronics/img21.jpg"), 
        new item("washingmachine",5550,"Electronics",93,"electronics","assets/img/electronics/img22.jpg"), 
        new item("washingmachine",5550,"Electronics",94,"electronics","assets/img/electronics/img23.jpg"), 
        new item("washingmachine",5550,"Electronics",95,"electronics","assets/img/electronics/img24.jpg"), 
        new item("washingmachine",5550,"Electronics",96,"electronics","assets/img/electronics/img25.jpg"), 
        new item("Roomcooler",5550,"Electronics",97,"electronics","assets/img/electronics/img26.jpg"), 
        new item("roomcooler",5550,"Electronics",98,"electronics","assets/img/electronics/img27.jpg"), 
        new item("roomcooler",5550,"Electronics",99,"electronics","assets/img/electronics/img28.jpg"), 
       
]
